---
- name: Converge
  hosts: jsonplaceholderapiusers
  connection: local
  gather_facts: false
  pre_tasks:
    - debug:
        var: this_is_my_fact | mandatory 
- import_playbook: ../../playbook.yml
